import { AircraftModel } from '@/types/aircraft';

export const AIRCRAFT_PRESETS: Record<string, AircraftModel> = {
  delta_strike: {
    id: 'preset-delta_strike',
    name: 'Delta Strike Fighter',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-delta',
      name: 'Delta Fuselage',
      visible: true,
      locked: false,
      length: 12.0,
      radius: 2.2,
      noseRoundness: 0.75,
      noseAngle: 90,
      noseZ: 0.0,
      noseY: 0.0,
      tail: 0.3,
      tailZ: 0.0,
      tailY: 0.0,
      sec1_w: 1.8,
      sec1_h: 1.6,
      sec1_x: 0.20,
      sec2_w: 1.8,
      sec2_h: 1.6,
      sec2_x: 0.50,
      sec3_w: 1.4,
      sec3_h: 1.4,
      sec3_x: 0.80,
      color: '#0284C7',
      sections: [
        { id: 'sec-0', name: 'Nose Dome', xPos: 0.0, width: 0.8, height: 0.7, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Cockpit Station', xPos: 0.20, width: 1.8, height: 1.6, nExp: 2.2, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Mid Fuselage', xPos: 0.50, width: 1.8, height: 1.6, nExp: 2.2, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Aft Station', xPos: 0.80, width: 1.4, height: 1.4, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-delta',
        name: 'Delta Main Wing',
        visible: true,
        locked: false,
        span: 14.0,
        rootChord: 6.8,
        tipChord: 0.8,
        sweep: 42.0,
        dihedral: 1.0,
        twist: 0,
        rootThickness: 9,
        tipThickness: 6,
        rootCamber: 1,
        tipCamber: 0,
        airfoilName: 'NACA 0009',
        rootPos: [3.2 - 6.0, 0, 0],
        color: '#0284C7',
        winglets: { enabled: true, height: 1.4, root: 0.8, tip: 0.3, sweep: 30.0, cant: 12.0, filletRadius: 0.60 },
      },
    ],
    tails: [
      {
        id: 'tail-delta',
        name: 'Vertical Fin',
        visible: true,
        locked: false,
        type: 'conventional',
        horizontalSpan: 0.1,
        horizontalChord: 0.1,
        verticalHeight: 4.2,
        verticalChord: 3.6,
        sweep: 48.0,
        dihedral: 90,
        position: [7.2 - 6.0, 0, 0.4],
        color: '#0369A1',
      },
    ],
    engines: [
      {
        id: 'eng-delta-1',
        name: 'Jet Engine',
        visible: true,
        locked: false,
        type: 'turbojet',
        diameter: 1.1,
        length: 4.2,
        position: [4.5, 0, 0],
        pylonHeight: 0,
        pylonWidth: 0,
        fanBlades: 0,
        color: '#475569',
      },
    ],
    gear: {
      id: 'gear-delta',
      name: 'Tricycle Gear',
      visible: true,
      locked: false,
      noseGear: { position: [-3.5, 0, -1.2], strutLength: 1.3, wheelDiameter: 0.5 },
      mainGear: { position: [1.8, 0, -1.3], strutLength: 1.4, wheelDiameter: 0.7, trackWidth: 3.2, retractionAngle: 0 },
      color: '#64748B',
    },
  },

  commercial: {
    id: 'preset-commercial',
    name: 'Commercial Transport Airliner',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-comm',
      name: 'Airliner Fuselage',
      visible: true,
      locked: false,
      length: 32.0,
      radius: 3.5,
      noseRoundness: 0.95,
      noseAngle: 90,
      noseZ: -0.30,
      noseY: 0.0,
      tail: 0.4,
      tailZ: 0.40,
      tailY: 0.0,
      sec1_w: 3.0,
      sec1_h: 3.0,
      sec1_x: 0.15,
      sec2_w: 3.0,
      sec2_h: 3.0,
      sec2_x: 0.55,
      sec3_w: 1.8,
      sec3_h: 1.8,
      sec3_x: 0.85,
      color: '#38BDF8',
      sections: [
        { id: 'sec-0', name: 'Cockpit Nose', xPos: 0.0, width: 2.1, height: 2.1, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Forward Cabin', xPos: 0.15, width: 3.0, height: 3.0, nExp: 2.4, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Mid Cabin', xPos: 0.55, width: 3.0, height: 3.0, nExp: 2.4, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Aft Fuselage', xPos: 0.85, width: 1.8, height: 1.8, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-comm',
        name: 'Swept Airliner Wing',
        visible: true,
        locked: false,
        span: 30.0,
        rootChord: 5.2,
        tipChord: 1.8,
        sweep: 24.0,
        dihedral: 3.5,
        twist: -2.5,
        rootThickness: 12,
        tipThickness: 9,
        rootCamber: 2,
        tipCamber: 1,
        airfoilName: 'NACA 2412',
        rootPos: [10.5 - 16.0, 0, -0.4],
        color: '#0284C7',
        winglets: { enabled: true, height: 1.8, root: 1.2, tip: 0.5, sweep: 35.0, cant: 18.0, filletRadius: 1.10 },
      },
    ],
    tails: [
      {
        id: 'tail-comm',
        name: 'Empennage',
        visible: true,
        locked: false,
        type: 'conventional',
        horizontalSpan: 10.5,
        horizontalChord: 2.6,
        verticalHeight: 5.2,
        verticalChord: 3.8,
        sweep: 35.0,
        dihedral: 3,
        position: [25.0 - 16.0, 0, 0.8],
        color: '#0369A1',
      },
    ],
    engines: [
      {
        id: 'eng-comm-1',
        name: 'Port Turbofan',
        visible: true,
        locked: false,
        type: 'turbofan',
        diameter: 1.8,
        length: 3.4,
        position: [-3.0, -5.2, -1.4],
        pylonHeight: 0.7,
        pylonWidth: 0.3,
        fanBlades: 18,
        color: '#475569',
      },
      {
        id: 'eng-comm-2',
        name: 'Starboard Turbofan',
        visible: true,
        locked: false,
        type: 'turbofan',
        diameter: 1.8,
        length: 3.4,
        position: [-3.0, 5.2, -1.4],
        pylonHeight: 0.7,
        pylonWidth: 0.3,
        fanBlades: 18,
        color: '#475569',
      },
    ],
    gear: {
      id: 'gear-comm',
      name: 'Airliner Gear',
      visible: true,
      locked: false,
      noseGear: { position: [-11.5, 0, -2.1], strutLength: 2.0, wheelDiameter: 0.75 },
      mainGear: { position: [0.5, 0, -2.2], strutLength: 2.1, wheelDiameter: 1.1, trackWidth: 6.8, retractionAngle: 0 },
      color: '#64748B',
    },
  },
};
