import { AircraftModel } from '@/types/aircraft';

export const AIRCRAFT_PRESETS: Record<string, AircraftModel> = {
  delta_strike: {
    id: 'preset-delta_strike',
    name: 'Delta Strike Fighter',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-delta',
      name: 'Delta Fuselage',
      visible: true,
      locked: false,
      length: 12.0,
      radius: 2.2,
      noseRoundness: 0.75,
      noseAngle: 90,
      noseZ: 0.0,
      noseY: 0.0,
      tail: 0.3,
      tailZ: 0.0,
      tailY: 0.0,
      sec1_w: 1.8,
      sec1_h: 1.6,
      sec1_x: 0.20,
      sec2_w: 1.8,
      sec2_h: 1.6,
      sec2_x: 0.50,
      sec3_w: 1.4,
      sec3_h: 1.4,
      sec3_x: 0.80,
      color: '#0284C7',
      sections: [
        { id: 'sec-0', name: 'Nose Dome', xPos: 0.0, width: 0.8, height: 0.7, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Cockpit Station', xPos: 0.20, width: 1.8, height: 1.6, nExp: 2.2, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Mid Fuselage', xPos: 0.50, width: 1.8, height: 1.6, nExp: 2.2, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Aft Station', xPos: 0.80, width: 1.4, height: 1.4, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-delta',
        name: 'Delta Main Wing (Mid Wing)',
        visible: true,
        locked: false,
        mountConfig: 'mid',
        span: 14.0,
        rootChord: 6.8,
        tipChord: 0.8,
        sweep: 42.0,
        dihedral: 1.0,
        twist: 0,
        rootThickness: 9,
        tipThickness: 6,
        rootCamber: 1,
        tipCamber: 0,
        airfoilName: 'NACA 0009',
        rootPos: [3.2, 0, 0],
        color: '#0284C7',
        winglets: { enabled: true, height: 1.4, root: 0.8, tip: 0.3, sweep: 30.0, cant: 12.0, filletRadius: 0.60 },
      },
    ],
    tails: [
      {
        id: 'tail-delta',
        name: 'Vertical Fin',
        visible: true,
        locked: false,
        type: 'conventional',
        horizontalSpan: 0.0,
        horizontalChord: 0.0,
        verticalHeight: 4.2,
        verticalChord: 3.6,
        sweep: 48.0,
        dihedral: 0,
        position: [10.2, 0, 0.4],
        color: '#0369A1',
      },
    ],
    engines: [
      {
        id: 'eng-delta-1',
        name: 'Jet Engine',
        visible: true,
        locked: false,
        type: 'turbojet',
        diameter: 1.1,
        length: 4.2,
        position: [10.5, 0, 0],
        pylonHeight: 0.3,
        pylonWidth: 0.2,
        fanBlades: 0,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#475569',
      },
    ],
  },

  commercial: {
    id: 'preset-commercial',
    name: 'Commercial Transport Airliner',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-comm',
      name: 'Airliner Fuselage',
      visible: true,
      locked: false,
      length: 32.0,
      radius: 3.5,
      noseRoundness: 0.95,
      noseAngle: 90,
      noseZ: -0.30,
      noseY: 0.0,
      tail: 0.4,
      tailZ: 0.40,
      tailY: 0.0,
      sec1_w: 3.0,
      sec1_h: 3.0,
      sec1_x: 0.15,
      sec2_w: 3.0,
      sec2_h: 3.0,
      sec2_x: 0.55,
      sec3_w: 1.8,
      sec3_h: 1.8,
      sec3_x: 0.85,
      color: '#38BDF8',
      sections: [
        { id: 'sec-0', name: 'Cockpit Nose', xPos: 0.0, width: 2.1, height: 2.1, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Forward Cabin', xPos: 0.15, width: 3.0, height: 3.0, nExp: 2.4, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Mid Cabin', xPos: 0.55, width: 3.0, height: 3.0, nExp: 2.4, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Aft Fuselage', xPos: 0.85, width: 1.8, height: 1.8, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-comm',
        name: 'Swept Airliner Wing (Low Wing)',
        visible: true,
        locked: false,
        mountConfig: 'low',
        span: 30.0,
        rootChord: 5.2,
        tipChord: 1.8,
        sweep: 24.0,
        dihedral: 3.5,
        twist: -2.5,
        rootThickness: 12,
        tipThickness: 9,
        rootCamber: 2,
        tipCamber: 1,
        airfoilName: 'NACA 2412',
        rootPos: [10.5, 0, -0.6],
        color: '#0284C7',
        winglets: { enabled: true, height: 1.8, root: 1.2, tip: 0.5, sweep: 35.0, cant: 18.0, filletRadius: 1.10 },
      },
    ],
    tails: [
      {
        id: 'tail-comm',
        name: 'Empennage',
        visible: true,
        locked: false,
        type: 'conventional',
        horizontalSpan: 10.5,
        horizontalChord: 2.6,
        verticalHeight: 5.2,
        verticalChord: 3.8,
        sweep: 35.0,
        dihedral: 3,
        position: [25.0, 0, 0.8],
        color: '#0369A1',
      },
    ],
    engines: [
      {
        id: 'eng-comm-1',
        name: 'Port Turbofan',
        visible: true,
        locked: false,
        type: 'turbofan',
        diameter: 1.8,
        length: 3.4,
        position: [-3.0, -5.2, -1.4],
        pylonHeight: 0.45,
        pylonWidth: 0.25,
        fanBlades: 18,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#475569',
      },
      {
        id: 'eng-comm-2',
        name: 'Starboard Turbofan',
        visible: true,
        locked: false,
        type: 'turbofan',
        diameter: 1.8,
        length: 3.4,
        position: [-3.0, 5.2, -1.4],
        pylonHeight: 0.45,
        pylonWidth: 0.25,
        fanBlades: 18,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#475569',
      },
    ],
  },

  high_wing_cargo: {
    id: 'preset-high_wing_cargo',
    name: 'Tactical Cargo Airlifter (High Wing)',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-cargo',
      name: 'Cargo Fuselage',
      visible: true,
      locked: false,
      length: 28.0,
      radius: 3.2,
      noseRoundness: 0.85,
      noseAngle: 90,
      noseZ: -0.2,
      noseY: 0.0,
      tail: 0.5,
      tailZ: 0.8,
      tailY: 0.0,
      sec1_w: 3.2,
      sec1_h: 3.0,
      sec1_x: 0.15,
      sec2_w: 3.2,
      sec2_h: 3.0,
      sec2_x: 0.60,
      sec3_w: 2.2,
      sec3_h: 2.0,
      sec3_x: 0.85,
      color: '#475569',
      sections: [
        { id: 'sec-0', name: 'Blunt Nose', xPos: 0.0, width: 2.2, height: 2.0, nExp: 2.2, shapeType: 'rounded_rectangle', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Flight Deck', xPos: 0.15, width: 3.2, height: 3.0, nExp: 2.6, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Cargo Bay', xPos: 0.60, width: 3.2, height: 3.0, nExp: 2.6, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Ramp Up-Sweep', xPos: 0.85, width: 2.2, height: 2.0, nExp: 2.2, shapeType: 'ellipse', yOffset: 0, zOffset: 0.4 },
      ],
    },
    wings: [
      {
        id: 'wing-cargo',
        name: 'Shoulder Mount Wing (High Wing)',
        visible: true,
        locked: false,
        mountConfig: 'high',
        span: 32.0,
        rootChord: 4.8,
        tipChord: 2.0,
        sweep: 12.0,
        dihedral: -1.5, // Slight anhedral for high-wing lateral roll damping
        twist: -2.0,
        rootThickness: 15,
        tipThickness: 10,
        rootCamber: 2,
        tipCamber: 1,
        airfoilName: 'NACA 2415',
        rootPos: [8.5, 0, 1.4], // Mounted atop fuselage
        color: '#334155',
        winglets: { enabled: true, height: 1.5, root: 1.1, tip: 0.4, sweep: 30.0, cant: 15.0, filletRadius: 0.8 },
      },
    ],
    tails: [
      {
        id: 'tail-cargo',
        name: 'High T-Tail',
        visible: true,
        locked: false,
        type: 't-tail',
        horizontalSpan: 11.0,
        horizontalChord: 2.4,
        verticalHeight: 5.8,
        verticalChord: 3.6,
        sweep: 32.0,
        dihedral: 0,
        position: [23.0, 0, 0.6],
        color: '#1E293B',
      },
    ],
    engines: [
      {
        id: 'eng-cargo-1',
        name: 'Port Inner Turboprop',
        visible: true,
        locked: false,
        type: 'propeller',
        diameter: 1.6,
        length: 3.0,
        position: [-4.0, -5.5, 0.8],
        pylonHeight: 0.35,
        pylonWidth: 0.25,
        fanBlades: 6,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#0F172A',
      },
      {
        id: 'eng-cargo-2',
        name: 'Starboard Inner Turboprop',
        visible: true,
        locked: false,
        type: 'propeller',
        diameter: 1.6,
        length: 3.0,
        position: [-4.0, 5.5, 0.8],
        pylonHeight: 0.35,
        pylonWidth: 0.25,
        fanBlades: 6,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#0F172A',
      },
    ],
  },

  fighter: {
    id: 'preset-fighter',
    name: 'Supersonic Air Superiority Fighter',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-fighter',
      name: 'Chined Fuselage',
      visible: true,
      locked: false,
      length: 16.0,
      radius: 2.0,
      noseRoundness: 0.6,
      noseAngle: 90,
      noseZ: -0.1,
      noseY: 0.0,
      tail: 0.2,
      tailZ: 0.0,
      tailY: 0.0,
      sec1_w: 1.8,
      sec1_h: 1.3,
      sec1_x: 0.25,
      sec2_w: 2.4,
      sec2_h: 1.4,
      sec2_x: 0.55,
      sec3_w: 2.0,
      sec3_h: 1.1,
      sec3_x: 0.85,
      color: '#334155',
      sections: [
        { id: 'sec-0', name: 'Radar Radome', xPos: 0.0, width: 0.7, height: 0.6, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Canopy Deck', xPos: 0.25, width: 1.8, height: 1.3, nExp: 2.4, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Mid Wing-Body', xPos: 0.55, width: 2.4, height: 1.4, nExp: 2.8, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Nozzle Bay', xPos: 0.85, width: 2.0, height: 1.1, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-fighter',
        name: 'Cropped Delta Wing (Mid Wing)',
        visible: true,
        locked: false,
        mountConfig: 'mid',
        span: 12.5,
        rootChord: 5.5,
        tipChord: 1.2,
        sweep: 45.0,
        dihedral: 0.0,
        twist: -1.0,
        rootThickness: 6,
        tipThickness: 4,
        rootCamber: 0,
        tipCamber: 0,
        airfoilName: 'NACA 0006',
        rootPos: [8.5, 0, 0.0],
        color: '#475569',
        winglets: { enabled: false, height: 0, root: 0, tip: 0, sweep: 0, cant: 0, filletRadius: 0 },
      },
    ],
    tails: [
      {
        id: 'tail-fighter',
        name: 'Twin Vertical Tails',
        visible: true,
        locked: false,
        type: 'twin-tail',
        horizontalSpan: 4.8,
        horizontalChord: 2.2,
        verticalHeight: 3.2,
        verticalChord: 2.4,
        sweep: 42.0,
        dihedral: 0,
        position: [13.2, 0, 0.2],
        color: '#1E293B',
      },
    ],
    engines: [
      {
        id: 'eng-fighter-1',
        name: 'Port Afterburning Turbofan',
        visible: true,
        locked: false,
        type: 'turbojet',
        diameter: 0.95,
        length: 4.5,
        position: [11.8, -0.7, 0.0],
        pylonHeight: 0.25,
        pylonWidth: 0.15,
        fanBlades: 0,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#0F172A',
      },
      {
        id: 'eng-fighter-2',
        name: 'Starboard Afterburning Turbofan',
        visible: true,
        locked: false,
        type: 'turbojet',
        diameter: 0.95,
        length: 4.5,
        position: [11.8, 0.7, 0.0],
        pylonHeight: 0.25,
        pylonWidth: 0.15,
        fanBlades: 0,
        attachToWing: true,
        mountStyle: 'underwing',
        color: '#0F172A',
      },
    ],
  },

  glider: {
    id: 'preset-glider',
    name: 'High-Performance Sailplane (High Wing)',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-glider',
      name: 'Streamlined Pod & Boom',
      visible: true,
      locked: false,
      length: 8.0,
      radius: 0.9,
      noseRoundness: 0.9,
      noseAngle: 90,
      noseZ: 0.0,
      noseY: 0.0,
      tail: 0.15,
      tailZ: 0.1,
      tailY: 0.0,
      sec1_w: 0.8,
      sec1_h: 0.9,
      sec1_x: 0.20,
      sec2_w: 0.8,
      sec2_h: 0.8,
      sec2_x: 0.40,
      sec3_w: 0.3,
      sec3_h: 0.3,
      sec3_x: 0.80,
      color: '#F8FAFC',
      sections: [
        { id: 'sec-0', name: 'Nose Cone', xPos: 0.0, width: 0.4, height: 0.5, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-1', name: 'Cockpit Canopy', xPos: 0.20, width: 0.8, height: 0.9, nExp: 2.2, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Wing Attachment', xPos: 0.40, width: 0.8, height: 0.8, nExp: 2.0, shapeType: 'ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Tail Boom', xPos: 0.80, width: 0.3, height: 0.3, nExp: 2.0, shapeType: 'circle', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-glider',
        name: 'High Aspect Ratio Wing (High Wing)',
        visible: true,
        locked: false,
        mountConfig: 'high',
        span: 20.0,
        rootChord: 1.2,
        tipChord: 0.45,
        sweep: 2.0,
        dihedral: 2.5,
        twist: -2.0,
        rootThickness: 13,
        tipThickness: 9,
        rootCamber: 3,
        tipCamber: 2,
        airfoilName: 'NACA 4412',
        rootPos: [3.2, 0, 0.45],
        color: '#E2E8F0',
        winglets: { enabled: true, height: 0.8, root: 0.4, tip: 0.15, sweep: 35.0, cant: 15.0, filletRadius: 0.4 },
      },
    ],
    tails: [
      {
        id: 'tail-glider',
        name: 'T-Tail Sailplane Empennage',
        visible: true,
        locked: false,
        type: 't-tail',
        horizontalSpan: 3.2,
        horizontalChord: 0.65,
        verticalHeight: 1.8,
        verticalChord: 0.8,
        sweep: 15.0,
        dihedral: 0,
        position: [7.4, 0, 0.1],
        color: '#CBD5E1',
      },
    ],
    engines: [],
  },

  drone: {
    id: 'preset-drone',
    name: 'Long-Endurance Tactical UAV (High Wing)',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-drone',
      name: 'Sensor Bulb Fuselage',
      visible: true,
      locked: false,
      length: 7.5,
      radius: 1.1,
      noseRoundness: 0.85,
      noseAngle: 90,
      noseZ: 0.1,
      noseY: 0.0,
      tail: 0.25,
      tailZ: 0.0,
      tailY: 0.0,
      sec1_w: 1.1,
      sec1_h: 1.1,
      sec1_x: 0.18,
      sec2_w: 1.0,
      sec2_h: 1.0,
      sec2_x: 0.50,
      sec3_w: 0.5,
      sec3_h: 0.5,
      sec3_x: 0.85,
      color: '#64748B',
      sections: [
        { id: 'sec-0', name: 'Bulb Nose', xPos: 0.0, width: 0.9, height: 0.9, nExp: 2.0, shapeType: 'circle', yOffset: 0, zOffset: 0.1 },
        { id: 'sec-1', name: 'Avionics Bay', xPos: 0.18, width: 1.1, height: 1.1, nExp: 2.2, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-2', name: 'Payload Bay', xPos: 0.50, width: 1.0, height: 1.0, nExp: 2.0, shapeType: 'super_ellipse', yOffset: 0, zOffset: 0 },
        { id: 'sec-3', name: 'Aft Engine Mount', xPos: 0.85, width: 0.5, height: 0.5, nExp: 2.0, shapeType: 'circle', yOffset: 0, zOffset: 0 },
      ],
    },
    wings: [
      {
        id: 'wing-drone',
        name: 'Endurance Wing (High Wing)',
        visible: true,
        locked: false,
        mountConfig: 'high',
        span: 16.0,
        rootChord: 1.6,
        tipChord: 0.7,
        sweep: 5.0,
        dihedral: 1.5,
        twist: -1.5,
        rootThickness: 14,
        tipThickness: 10,
        rootCamber: 3,
        tipCamber: 1,
        airfoilName: 'NACA 4412',
        rootPos: [3.75, 0, 0.55],
        color: '#475569',
        winglets: { enabled: true, height: 0.9, root: 0.6, tip: 0.2, sweep: 25.0, cant: 12.0, filletRadius: 0.4 },
      },
    ],
    tails: [
      {
        id: 'tail-drone',
        name: 'Inverted V-Tail',
        visible: true,
        locked: false,
        type: 'v-tail',
        horizontalSpan: 3.5,
        horizontalChord: 0.9,
        verticalHeight: 1.8,
        verticalChord: 0.9,
        sweep: 28.0,
        dihedral: 35.0,
        position: [6.95, 0, 0.0],
        color: '#334155',
      },
    ],
    engines: [
      {
        id: 'eng-drone-pusher',
        name: 'Pusher Propeller',
        visible: true,
        locked: false,
        type: 'propeller',
        diameter: 1.2,
        length: 1.5,
        position: [7.15, 0, 0.0],
        pylonHeight: 0,
        pylonWidth: 0,
        fanBlades: 3,
        color: '#0F172A',
      },
    ],
  },

  blank: {
    id: 'preset-blank',
    name: 'Blank Canvas',
    version: '1.0',
    units: 'metric',
    fuselage: {
      id: 'fus-blank',
      name: 'Standard Fuselage',
      visible: true,
      locked: false,
      length: 10.0,
      radius: 1.5,
      noseRoundness: 0.8,
      noseAngle: 90,
      noseZ: 0.0,
      noseY: 0.0,
      tail: 0.3,
      tailZ: 0.0,
      tailY: 0.0,
      sec1_w: 1.2,
      sec1_h: 1.2,
      sec1_x: 0.20,
      sec2_w: 1.2,
      sec2_h: 1.2,
      sec2_x: 0.50,
      sec3_w: 1.0,
      sec3_h: 1.0,
      sec3_x: 0.80,
      color: '#475569',
      sections: [],
    },
    wings: [],
    tails: [],
    engines: [],
  },
};
