'use client';

import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { AircraftModel } from '@/types/aircraft';
import { generateFuselageGeometry } from '@/engine/generators/fuselageGenerator';
import { generateWingGeometry } from '@/engine/generators/wingGenerator';
import { generateTailGeometry } from '@/engine/generators/tailGenerator';
import { generateEngineGeometry } from '@/engine/generators/engineGenerator';
import { Plane, Layers } from 'lucide-react';

interface AircraftThumbnailProps {
  model: AircraftModel;
  width?: number;
  height?: number;
  className?: string;
  viewMode?: 'iso' | 'top';
  interactive?: boolean;
}

/**
 * Singleton Offscreen WebGL Renderer for High-Performance 3D Aircraft Thumbnails in Light Studio Theme.
 * Renders the EXACT 3D CAD mesh geometry generated by OpenVSP generators.
 */
class OffscreenThumbnailRenderer {
  private static instance: OffscreenThumbnailRenderer;
  private renderer: THREE.WebGLRenderer | null = null;
  private canvas: HTMLCanvasElement | null = null;

  public static getInstance(): OffscreenThumbnailRenderer {
    if (!OffscreenThumbnailRenderer.instance) {
      OffscreenThumbnailRenderer.instance = new OffscreenThumbnailRenderer();
    }
    return OffscreenThumbnailRenderer.instance;
  }

  private getRenderer(width: number, height: number): THREE.WebGLRenderer | null {
    if (typeof window === 'undefined') return null;
    try {
      if (!this.canvas) {
        this.canvas = document.createElement('canvas');
      }
      if (!this.renderer) {
        this.renderer = new THREE.WebGLRenderer({
          canvas: this.canvas,
          antialias: true,
          alpha: true,
          preserveDrawingBuffer: true,
          powerPreference: 'high-performance',
        });
      }
      this.renderer.setPixelRatio(1);
      this.renderer.setSize(width, height, false);
      return this.renderer;
    } catch (e) {
      console.warn('WebGL not available for thumbnail rendering', e);
      return null;
    }
  }

  public renderModelToCanvas(
    model: AircraftModel,
    targetCanvas: HTMLCanvasElement,
    width: number,
    height: number,
    viewMode: 'iso' | 'top' = 'iso'
  ): boolean {
    if (!model) return false;

    const dpr = typeof window !== 'undefined' ? Math.min(window.devicePixelRatio || 1, 2) : 1;
    const renderWidth = Math.max(32, Math.floor(width * dpr));
    const renderHeight = Math.max(32, Math.floor(height * dpr));

    const renderer = this.getRenderer(renderWidth, renderHeight);
    if (!renderer) return false;

    const scene = new THREE.Scene();
    const group = new THREE.Group();

    let hasVisibleGeometry = false;

    // 1. Fuselage Geometry
    if (model.fuselage && model.fuselage.visible) {
      try {
        const geo = generateFuselageGeometry(model.fuselage);
        const mat = new THREE.MeshStandardMaterial({
          color: model.fuselage.color || '#0284C7',
          roughness: 0.3,
          metalness: 0.35,
          side: THREE.DoubleSide,
        });
        group.add(new THREE.Mesh(geo, mat));
        hasVisibleGeometry = true;
      } catch (e) {
        console.warn('Failed to generate fuselage thumbnail geo', e);
      }
    }

    // 2. Main Wings Geometry
    if (model.wings) {
      model.wings
        .filter((w) => w.visible)
        .forEach((w) => {
          try {
            const geo = generateWingGeometry(w, false, 'low');
            const mat = new THREE.MeshStandardMaterial({
              color: w.color || '#0284C7',
              roughness: 0.28,
              metalness: 0.38,
              side: THREE.DoubleSide,
            });
            group.add(new THREE.Mesh(geo, mat));
            hasVisibleGeometry = true;
          } catch (e) {
            console.warn('Failed to generate wing thumbnail geo', e);
          }
        });
    }

    // 3. Tails Geometry (Conventional, V-tail, T-tail, Twin-tail)
    if (model.tails) {
      model.tails
        .filter((t) => t.visible)
        .forEach((t) => {
          try {
            const geo = generateTailGeometry(t);
            const mat = new THREE.MeshStandardMaterial({
              color: t.color || '#0369A1',
              roughness: 0.3,
              metalness: 0.35,
              side: THREE.DoubleSide,
            });
            group.add(new THREE.Mesh(geo, mat));
            hasVisibleGeometry = true;
          } catch (e) {
            console.warn('Failed to generate tail thumbnail geo', e);
          }
        });
    }

    // 4. Engine Geometry
    if (model.engines) {
      model.engines
        .filter((e) => e.visible)
        .forEach((e) => {
          try {
            const geo = generateEngineGeometry(e, model.wings);
            const mat = new THREE.MeshStandardMaterial({
              color: e.color || '#1E293B',
              roughness: 0.35,
              metalness: 0.6,
              side: THREE.DoubleSide,
            });
            group.add(new THREE.Mesh(geo, mat));
            hasVisibleGeometry = true;
          } catch (e) {
            console.warn('Failed to generate engine thumbnail geo', e);
          }
        });
    }

    if (!hasVisibleGeometry) {
      return false;
    }

    scene.add(group);

    // Compute bounding box and center aircraft group
    const box = new THREE.Box3().setFromObject(group);
    if (box.isEmpty()) {
      scene.traverse((obj) => {
        if (obj instanceof THREE.Mesh) {
          obj.geometry?.dispose();
          if (Array.isArray(obj.material)) obj.material.forEach((m) => m.dispose());
          else obj.material?.dispose();
        }
      });
      return false;
    }

    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());
    group.position.sub(center);

    const maxDim = Math.max(size.x, size.y, size.z, 1.0);
    const camera = new THREE.PerspectiveCamera(35, renderWidth / renderHeight, 0.1, maxDim * 25);

    if (viewMode === 'top') {
      camera.position.set(0, maxDim * 2.2, 0);
      camera.up.set(-1, 0, 0);
      camera.lookAt(0, 0, 0);
    } else {
      // 3/4 Isometric CAD Studio View: Looking from front-left-above for optimal aerospace perspective
      camera.position.set(-maxDim * 1.5, maxDim * 1.05, maxDim * 1.4);
      camera.up.set(0, 1, 0);
      camera.lookAt(0, 0, 0);
    }

    // Studio Lighting setup for crisp high-end CAD rendering
    const ambLight = new THREE.AmbientLight(0xffffff, 1.4);
    scene.add(ambLight);

    // Key Light (Front-Left-Top)
    const dirLight1 = new THREE.DirectionalLight(0xffffff, 1.8);
    dirLight1.position.set(-maxDim * 2, maxDim * 3, maxDim * 2.5);
    scene.add(dirLight1);

    // Rim/Accent Light (Aft-Right with sky tint)
    const dirLight2 = new THREE.DirectionalLight(0x38bdf8, 1.2);
    dirLight2.position.set(maxDim * 2.5, maxDim * 1.5, -maxDim * 2);
    scene.add(dirLight2);

    // Top Soft Light
    const topLight = new THREE.DirectionalLight(0xffffff, 0.9);
    topLight.position.set(0, maxDim * 4, 0);
    scene.add(topLight);

    // Bottom Ambient bounce
    const bottomLight = new THREE.DirectionalLight(0x94a3b8, 0.4);
    bottomLight.position.set(0, -maxDim * 2, 0);
    scene.add(bottomLight);

    renderer.clear();
    renderer.render(scene, camera);

    // Copy offscreen rendered canvas buffer to target canvas
    targetCanvas.width = renderWidth;
    targetCanvas.height = renderHeight;
    const ctx = targetCanvas.getContext('2d');
    if (ctx && this.canvas) {
      ctx.clearRect(0, 0, renderWidth, renderHeight);
      ctx.drawImage(this.canvas, 0, 0);
    }

    // Clean up scene geometries & materials
    scene.traverse((obj) => {
      if (obj instanceof THREE.Mesh) {
        obj.geometry?.dispose();
        if (Array.isArray(obj.material)) obj.material.forEach((m) => m.dispose());
        else obj.material?.dispose();
      }
    });

    return true;
  }
}

/**
 * High-precision exact 3D CAD Preview Thumbnail component in Light Theme.
 * Uses offscreen WebGL rendering of the actual 3D model geometries for 100% accurate thumbnails.
 */
export function AircraftThumbnail({
  model,
  width = 64,
  height = 64,
  className = '',
  viewMode = 'iso',
}: AircraftThumbnailProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [rendered, setRendered] = useState(false);

  useEffect(() => {
    if (!model || !canvasRef.current) return;
    const success = OffscreenThumbnailRenderer.getInstance().renderModelToCanvas(
      model,
      canvasRef.current,
      width,
      height,
      viewMode
    );
    setRendered(success);
  }, [model, width, height, viewMode]);

  if (!model) return null;

  return (
    <div
      className={`relative flex items-center justify-center rounded-2xl bg-gradient-to-br from-slate-50 via-sky-50/40 to-slate-100/90 border border-slate-250/70 shadow-sm overflow-hidden select-none flex-shrink-0 group ${className}`}
      style={{ width, height }}
    >
      {/* Background Light CAD Studio Grid */}
      <svg
        width="100%"
        height="100%"
        className="absolute inset-0 w-full h-full pointer-events-none opacity-50"
      >
        <defs>
          <pattern
            id={`grid-light-${model.id || 'thumb'}`}
            width="12"
            height="12"
            patternUnits="userSpaceOnUse"
          >
            <path
              d="M 12 0 L 0 0 0 12"
              fill="none"
              stroke="#0284C7"
              strokeWidth="0.5"
              strokeOpacity="0.2"
            />
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill={`url(#grid-light-${model.id || 'thumb'})`} />
      </svg>

      {/* CAD Blueprint Corner Crosshairs */}
      <div className="absolute top-1.5 left-1.5 w-1.5 h-1.5 border-t border-l border-sky-400/50 pointer-events-none z-20" />
      <div className="absolute top-1.5 right-1.5 w-1.5 h-1.5 border-t border-r border-sky-400/50 pointer-events-none z-20" />
      <div className="absolute bottom-1.5 left-1.5 w-1.5 h-1.5 border-b border-l border-sky-400/50 pointer-events-none z-20" />
      <div className="absolute bottom-1.5 right-1.5 w-1.5 h-1.5 border-b border-r border-sky-400/50 pointer-events-none z-20" />

      {/* Rendered 3D Exact Aircraft Canvas */}
      <canvas
        ref={canvasRef}
        className={`w-full h-full relative z-10 object-contain transition-all duration-300 group-hover:scale-110 ${
          rendered ? 'opacity-100' : 'opacity-0 hidden'
        }`}
        style={{ width: '100%', height: '100%' }}
      />

      {/* Fallback stylized Blueprint silhouette when model is blank/empty */}
      {!rendered && (
        <div className="relative z-10 flex flex-col items-center justify-center text-sky-600/70 p-2 text-center">
          <Plane className="w-6 h-6 stroke-[1.5] text-sky-500/80 -rotate-45" />
          <span className="text-[9px] font-mono font-bold text-sky-700/70 mt-1 uppercase tracking-wider">
            Blueprint
          </span>
        </div>
      )}

      {/* Subtle Inner Border Glow */}
      <div className="absolute inset-0 rounded-2xl border border-sky-200/40 pointer-events-none z-20 shadow-inner" />
    </div>
  );
}
